package db.training.bob.service;

public enum FetchPlan {
	// Bearbeitungsbereich
	BB_REGIONALBEREICH,

	// BOB-Baumaßnahmen
	BOB_BBP_MASSNAHME,
	BOB_REGIONALBEREICH_FPL,
	BOB_BEARBEITUNGSBEREICH,
	BOB_BEARBEITER,
	BOB_KIGBAU,
	BOB_KORRIDOR_ZEITFENSTER,
	BOB_AUSFALLGRUND,
	BOB_AENDERUNGSDOKUMENTATION,
	BOB_ARBEITSLEISTUNG_REGIONALBEREICHE,
	BOB_TERMINE_BBP,
	BOB_TERMINE_GEVU,
	BOB_TERMINE_PEVU,
	BOB_UEBERGABEBLATT,
	BOB_BBZR,
	BOB_QS,
	BOB_ZUGCHARAKTERISTIK,

	// ZvF-Maßnahme
	ZVF_MN_VERSION,
	ZVF_MN_STRECKEN,
	ZVF_MN_ALLG_REGELUNGEN,
	ZVF_MN_BBPSTRECKE,
	ZVF_MN_STRECKE_STRECKEVZG,
	ZVF_ZUG_UMLEITWEG,
	ZVF_ZUG_ABWEICHUNG_HALT,
	ZVF_ZUG_ABWEICHUNG_REGELUNG,

	// Regionalbereich
	REGIONALBEREICH_BEARBEITUNGSBEREICH,

	// BBP Maßnahmen
	BBP_REGIONALBEREICH,
	BBP_REGELUNGEN,

	// Regelungen
	// -keine-

	// Übergabeblatt
	UEB_HEADER,
	UEB_HEADER_SENDER,
	UEB_HEADER_EMPFAENGER,
	UEB_BAUMASSNAHMEN,
	UEB_REGIONALBEREICHE,
	UEB_KNOTENZEITEN,
	UEB_BEARBEITUNGSSTATUS,
	UEB_MN_FPLO,
	UEB_MN_ZUEGE,

	UEB_ZUG_REGELWEG,
	UEB_ZUG_ABWEICHUNG_BAHNHOF,
	MN_FPLO_NIEDERLASSUNGEN,
	UEB_ZUG_ABWEICHUNG_HALT_BAHNHOF,

	// BBZR
	BBZR_HEADER,
	BBZR_BAUMASSNAHMEN,
	BBZR_MN_ZUEGE,

	// ////
	// OSB

	// SAP Maßnahme
	OSB_REGIONALBEREICH, 
	OSB_PAKET,
	OSB_BUENDEL,
	OSB_WEITERE_STRECKEN,
	OSB_BST_VON,
	OSB_BST_BIS,
	OSB_TOPPROJEKT,

	// Streckenband
	OSB_STRECKENBAND_MASSNAHME,

	// Gleissperrung
	OSB_GLEISSPERRUNG,
	OSB_GLEISSPERRUNG_MASSNAHME,
	OSB_GLEISSPERRUNG_BUENDEL,
	OSB_GLEISSPERRUNG_BAUSTELLEN,
	OSB_GLEISSPERRUNG_STRECKE,
	OSB_GLEISSPERRUNG_BETRIEBSWEISE,

	// Langsamfahrstelle
	OSB_LANGSAMFAHRSTELLE,
	OSB_LANGSAMFAHRSTELLE_MASSNAHME,
	OSB_LANGSAMFAHRSTELLE_VZGSTRECKE,
	
	// Oberleitung
	OSB_OBERLEITUNG,
	OSB_OBERLEITUNG_MASSNAHME,
	OSB_OBERLEITUNG_VZGSTRECKE,
	
	// Baustelle
	OSB_BAUSTELLE,
	OSB_BAUSTELLE_GLEISSPERRUNGEN,

	// Verkehrstageregelung
	OSB_VTR,

	// Bündel
	OSB_BUENDEL_GLEISSPERRUNGEN,

	// Fahrplanregelung
	OSB_FPL_BUENDEL, 
	OSB_FPL_REGIONALBEREICH, 
	OSB_FPL_BST_VON, 
	OSB_FPL_BST_BIS,
	OSB_FPL_UMLEITUNGEN,

	// UmleitungFahrplanregelungLink
	OSB_UML_FPL_FAHRPLANREGELUNG,
	OSB_UML_FPL_UMLEITUNG,

	// Umleitung
	OSB_UML_UMLEITUNGSWEGE, 
	OSB_UML_FAHRPLANREGELUNGEN,

	// Umleitungsweg
	OSB_UMLEITUNGSWEG_UMLEITUNGEN, 
	OSB_UMLEITUNGSWEG_VZGSTRECKE, 
	OSB_UMLEITUNGSWEG_BST_VON,
	OSB_UMLEITUNGSWEG_BST_BIS, 
	OSB_UMLEITUNGSWEG_FPL,

	// TOP-Projekt
	OSB_TOP_MASSNAHMEN,

	// Anmelder
	OSB_ANMELDER_USER, 
	OSB_ANMELDER_ANMELDERGRUPPE,

	// Paket
	OSB_PAKET_MASSNAHMEN
}
