//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.1-b02-fcs 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2008.09.24 at 11:44:26 AM CEST 
//

package db.training.bob.model.zvf;

import javax.xml.bind.annotation.XmlRegistry;

/**
 * This object contains factory methods for each Java content interface and Java element interface
 * generated in the org.example.testjaxb package.
 * <p>
 * An ObjectFactory allows you to programatically construct new instances of the Java representation
 * for XML content. The Java representation of XML content can consist of schema derived interfaces
 * and classes representing the binding of schema type definitions, element declarations and model
 * groups. Factory methods for each of these are provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

	/**
	 * Create a new ObjectFactory that can be used to create new instances of schema derived classes
	 * for package: org.example.testjaxb
	 * 
	 */
	public ObjectFactory() {
	}

	/**
	 * Create an instance of {@link Zug }
	 * 
	 */
	public Zug createZvfexportBaumassnahmenBaumassnahmeZuegeZug() {
		return new Zug();
	}

	/**
	 * Create an instance of {@link Uebergabeblatt.Header.Sender }
	 * 
	 */
	public Sender createZvfexportHeaderSender() {
		return new Sender();
	}

	/**
	 * Create an instance of {@link Regelweg }
	 * 
	 */
	public Regelweg createZvfexportBaumassnahmenBaumassnahmeZuegeZugRegelweg() {
		return new Regelweg();
	}

	/**
	 * Create an instance of {@link Version }
	 * 
	 */
	public Version createZvfexportBaumassnahmenBaumassnahmeVersion() {
		return new Version();
	}

	/**
	 * Create an instance of {@link Haltliste.Halt }
	 * 
	 */
	public Halt createZvfexportBaumassnahmenBaumassnahmeZuegeZugAbweichungHaltlisteHalt() {
		return new Halt();
	}

	/**
	 * Create an instance of {@link Niederlassung }
	 * 
	 */
	public Niederlassung createZvfexportBaumassnahmenBaumassnahmeFplonrNiederlassung() {
		return new Niederlassung();
	}

	/**
	 * Create an instance of {@link Zugdetails }
	 * 
	 */
	public Zugdetails createZvfexportBaumassnahmenBaumassnahmeZuegeZugZugdetails() {
		return new Zugdetails();
	}

	/**
	 * Create an instance of {@link Uebergabeblatt.Header }
	 * 
	 */
	public Header createZvfexportHeader() {
		return new Header();
	}

	/**
	 * Create an instance of {@link Uebergabeblatt }
	 * 
	 */
	public Uebergabeblatt createZvfexport() {
		return new Uebergabeblatt();
	}

	/**
	 * Create an instance of {@link Massnahme }
	 * 
	 */
	public Massnahme createZvfexportBaumassnahmenBaumassnahme() {
		return new Massnahme();
	}

	/**
	 * Create an instance of {@link Streckenabschnitte.Strecke }
	 * 
	 */
	public Strecke createZvfexportBaumassnahmenBaumassnahmeStreckenabschnitteStrecke() {
		return new Strecke();
	}

	/**
	 * Create an instance of {@link Abweichung }
	 * 
	 */
	public Abweichung createZvfexportBaumassnahmenBaumassnahmeZuegeZugAbweichung() {
		return new Abweichung();
	}

}
