CREATE VIEW ISA_BM AS
SELECT VORGANGSNR, FPLONR, STRECKEVZG, STRECKENABSCHNITT, ID, ARTDERMASSNAHME, BETRIEBSWEISE, BEGINNDATUM, ENDDATUM
FROM BM;
	 
CREATE VIEW ISA_BM_QSNR AS
SELECT BM_ID, QSNR
FROM BM_QSNR;
	
CREATE VIEW ISA_BM_KORRIDORZEITFENSTER AS
SELECT BM_ID, KORRIDORZEITFENSTER
FROM BM_KORRIDORZEITFENSTER;
	
CREATE VIEW ISA_MASSNAHME AS
SELECT * FROM MASSNAHME;
	
CREATE VIEW ISA_MASSNAHME_ZUG AS
SELECT MASSNAHME_ID, ZUG_ID
FROM MASSNAHME_ZUG;
	
	
CREATE VIEW ISA_ZUG AS
SELECT * FROM ZUG;
	
CREATE VIEW ISA_BST AS
SELECT * FROM BST;

COMMIT;