--EVUGRUPPE INSERT
insert into evugruppe values(HIBERNATE_SEQUENCE.NEXTVAL, 'DB Regio');
insert into evugruppe values(HIBERNATE_SEQUENCE.NEXTVAL, 'SchenkerDE');
insert into evugruppe values(HIBERNATE_SEQUENCE.NEXTVAL, 'SchenkerPL');
insert into evugruppe values(HIBERNATE_SEQUENCE.NEXTVAL, 'Netzintern');
insert into evugruppe values(HIBERNATE_SEQUENCE.NEXTVAL, 'S-Bln');
insert into evugruppe values(HIBERNATE_SEQUENCE.NEXTVAL, 'VEO, OLA');
insert into evugruppe values(HIBERNATE_SEQUENCE.NEXTVAL, 'ARR, PE');
insert into evugruppe values(HIBERNATE_SEQUENCE.NEXTVAL, 'AHG');
insert into evugruppe values(HIBERNATE_SEQUENCE.NEXTVAL, 'BSB');
insert into evugruppe values(HIBERNATE_SEQUENCE.NEXTVAL, 'DB Service');
insert into evugruppe values(HIBERNATE_SEQUENCE.NEXTVAL, 'Stadler');
insert into evugruppe values(HIBERNATE_SEQUENCE.NEXTVAL, 'DB Qualit.');
insert into evugruppe values(HIBERNATE_SEQUENCE.NEXTVAL, 'LUTRA');
insert into evugruppe values(HIBERNATE_SEQUENCE.NEXTVAL, 'ARR, ODEG');
insert into evugruppe values(HIBERNATE_SEQUENCE.NEXTVAL, 'LOCON');
insert into evugruppe values(HIBERNATE_SEQUENCE.NEXTVAL, 'Eichholz');
insert into evugruppe values(HIBERNATE_SEQUENCE.NEXTVAL, 'ekr');
insert into evugruppe values(HIBERNATE_SEQUENCE.NEXTVAL, 'VEO, NEB');
insert into evugruppe values(HIBERNATE_SEQUENCE.NEXTVAL, 'GVG');
insert into evugruppe values(HIBERNATE_SEQUENCE.NEXTVAL, 'B-S-L');
insert into evugruppe values(HIBERNATE_SEQUENCE.NEXTVAL, 'RFH');
insert into evugruppe values(HIBERNATE_SEQUENCE.NEXTVAL, 'EGP');
insert into evugruppe values(HIBERNATE_SEQUENCE.NEXTVAL, 'RCB');
insert into evugruppe values(HIBERNATE_SEQUENCE.NEXTVAL, 'AmE');
insert into evugruppe values(HIBERNATE_SEQUENCE.NEXTVAL, 'HR');
insert into evugruppe values(HIBERNATE_SEQUENCE.NEXTVAL, 'BEHALA');
insert into evugruppe values(HIBERNATE_SEQUENCE.NEXTVAL, 'L'||CHR(38)||'W');
insert into evugruppe values(HIBERNATE_SEQUENCE.NEXTVAL, 'DRE');
insert into evugruppe values(HIBERNATE_SEQUENCE.NEXTVAL, 'ETB');
insert into evugruppe values(HIBERNATE_SEQUENCE.NEXTVAL, 'ELS');
insert into evugruppe values(HIBERNATE_SEQUENCE.NEXTVAL, 'D '||CHR(38)||' D');
insert into evugruppe values(HIBERNATE_SEQUENCE.NEXTVAL, 'DISPO - TF');
insert into evugruppe values(HIBERNATE_SEQUENCE.NEXTVAL, 'HKX');
insert into evugruppe values(HIBERNATE_SEQUENCE.NEXTVAL, 'WEMEG');
insert into evugruppe values(HIBERNATE_SEQUENCE.NEXTVAL, 'Dynea');
insert into evugruppe values(HIBERNATE_SEQUENCE.NEXTVAL, 'PKP');
insert into evugruppe values(HIBERNATE_SEQUENCE.NEXTVAL, 'DeltaRail');
insert into evugruppe values(HIBERNATE_SEQUENCE.NEXTVAL, 'EnergyRail');
insert into evugruppe values(HIBERNATE_SEQUENCE.NEXTVAL, 'hvle');
insert into evugruppe values(HIBERNATE_SEQUENCE.NEXTVAL, 'PRESS');
insert into evugruppe values(HIBERNATE_SEQUENCE.NEXTVAL, 'Vattenfall');
insert into evugruppe values(HIBERNATE_SEQUENCE.NEXTVAL, 'CC-L');
insert into evugruppe values(HIBERNATE_SEQUENCE.NEXTVAL, 'locomore');
insert into evugruppe values(HIBERNATE_SEQUENCE.NEXTVAL, 'Eurobahn');
insert into evugruppe values(HIBERNATE_SEQUENCE.NEXTVAL, 'SuikerUnie');
insert into evugruppe values(HIBERNATE_SEQUENCE.NEXTVAL, 'CTLRail');
insert into evugruppe values(HIBERNATE_SEQUENCE.NEXTVAL, 'Bombardier');
insert into evugruppe values(HIBERNATE_SEQUENCE.NEXTVAL, 'EKO');
insert into evugruppe values(HIBERNATE_SEQUENCE.NEXTVAL, 'NME');
insert into evugruppe values(HIBERNATE_SEQUENCE.NEXTVAL, 'UBB');
insert into evugruppe values(HIBERNATE_SEQUENCE.NEXTVAL, 'BEF');
insert into evugruppe values(HIBERNATE_SEQUENCE.NEXTVAL, 'SLG');
insert into evugruppe values(HIBERNATE_SEQUENCE.NEXTVAL, 'LDC');
insert into evugruppe values(HIBERNATE_SEQUENCE.NEXTVAL, 'Ei.L.T.');
insert into evugruppe values(HIBERNATE_SEQUENCE.NEXTVAL, 'VEO, RBB');
insert into evugruppe values(HIBERNATE_SEQUENCE.NEXTVAL, 'Werk Cottb');
insert into evugruppe values(HIBERNATE_SEQUENCE.NEXTVAL, 'Werk Wtbg');
insert into evugruppe values(HIBERNATE_SEQUENCE.NEXTVAL, 'DGT');
insert into evugruppe values(HIBERNATE_SEQUENCE.NEXTVAL, 'MGW');
insert into evugruppe values(HIBERNATE_SEQUENCE.NEXTVAL, 'BBRail');
insert into evugruppe values(HIBERNATE_SEQUENCE.NEXTVAL, 'pethoplan');
insert into evugruppe values(HIBERNATE_SEQUENCE.NEXTVAL, 'TPR_Zusatz');
insert into evugruppe values(HIBERNATE_SEQUENCE.NEXTVAL, 'TRAPP');
insert into evugruppe values(HIBERNATE_SEQUENCE.NEXTVAL, 'EUROVIA');
insert into evugruppe values(HIBERNATE_SEQUENCE.NEXTVAL, 'BUG');
insert into evugruppe values(HIBERNATE_SEQUENCE.NEXTVAL, 'STRABAG');
insert into evugruppe values(HIBERNATE_SEQUENCE.NEXTVAL, 'STB');
insert into evugruppe values(HIBERNATE_SEQUENCE.NEXTVAL, 'Alpha Rail');
insert into evugruppe values(HIBERNATE_SEQUENCE.NEXTVAL, 'DB Bahnbau');
insert into evugruppe values(HIBERNATE_SEQUENCE.NEXTVAL, 'PCK Bln');
insert into evugruppe values(HIBERNATE_SEQUENCE.NEXTVAL, 'VMV');
insert into evugruppe values(HIBERNATE_SEQUENCE.NEXTVAL, 'SFH');
insert into evugruppe values(HIBERNATE_SEQUENCE.NEXTVAL, 'Ermefret');
insert into evugruppe values(HIBERNATE_SEQUENCE.NEXTVAL, 'U-Ost');
insert into evugruppe values(HIBERNATE_SEQUENCE.NEXTVAL, 'OttoDörner');
insert into evugruppe values(HIBERNATE_SEQUENCE.NEXTVAL, 'KGT');
insert into evugruppe values(HIBERNATE_SEQUENCE.NEXTVAL, 'GÖR (ZB)');
insert into evugruppe values(HIBERNATE_SEQUENCE.NEXTVAL, 'BZ Trassen');
insert into evugruppe values(HIBERNATE_SEQUENCE.NEXTVAL, 'SCHWEIZ');
insert into evugruppe values(HIBERNATE_SEQUENCE.NEXTVAL, 'DBRegioNRW');
insert into evugruppe values(HIBERNATE_SEQUENCE.NEXTVAL, 'RBH');
insert into evugruppe values(HIBERNATE_SEQUENCE.NEXTVAL, 'SchenkerJV');
insert into evugruppe values(HIBERNATE_SEQUENCE.NEXTVAL, 'GELSEN');
insert into evugruppe values(HIBERNATE_SEQUENCE.NEXTVAL, 'RLG');
insert into evugruppe values(HIBERNATE_SEQUENCE.NEXTVAL, 'EfW');
insert into evugruppe values(HIBERNATE_SEQUENCE.NEXTVAL, 'Bayer');
insert into evugruppe values(HIBERNATE_SEQUENCE.NEXTVAL, 'rail 4chem');
insert into evugruppe values(HIBERNATE_SEQUENCE.NEXTVAL, 'MEG');
insert into evugruppe values(HIBERNATE_SEQUENCE.NEXTVAL, 'Westbahn');
insert into evugruppe values(HIBERNATE_SEQUENCE.NEXTVAL, 'Hespertal');
insert into evugruppe values(HIBERNATE_SEQUENCE.NEXTVAL, 'TSD');
insert into evugruppe values(HIBERNATE_SEQUENCE.NEXTVAL, 'Rh-Sieg.Bn');
insert into evugruppe values(HIBERNATE_SEQUENCE.NEXTVAL, 'Rurtalbahn');
insert into evugruppe values(HIBERNATE_SEQUENCE.NEXTVAL, 'ABELLIO');
insert into evugruppe values(HIBERNATE_SEQUENCE.NEXTVAL, 'duis-rail');
insert into evugruppe values(HIBERNATE_SEQUENCE.NEXTVAL, 'WHE');
insert into evugruppe values(HIBERNATE_SEQUENCE.NEXTVAL, 'Crossrail Benelux');
insert into evugruppe values(HIBERNATE_SEQUENCE.NEXTVAL, 'ERS Rot.NL');
insert into evugruppe values(HIBERNATE_SEQUENCE.NEXTVAL, 'Railogic');
insert into evugruppe values(HIBERNATE_SEQUENCE.NEXTVAL, 'AStrans');
insert into evugruppe values(HIBERNATE_SEQUENCE.NEXTVAL, 'ACTS/NL');
insert into evugruppe values(HIBERNATE_SEQUENCE.NEXTVAL, 'HGK');
insert into evugruppe values(HIBERNATE_SEQUENCE.NEXTVAL, 'WestF-Bahn');
insert into evugruppe values(HIBERNATE_SEQUENCE.NEXTVAL, 'ARR, NL');
insert into evugruppe values(HIBERNATE_SEQUENCE.NEXTVAL, 'WESTIGO');
insert into evugruppe values(HIBERNATE_SEQUENCE.NEXTVAL, 'EH Gütervk');
insert into evugruppe values(HIBERNATE_SEQUENCE.NEXTVAL, 'B-Cargo');
insert into evugruppe values(HIBERNATE_SEQUENCE.NEXTVAL, 'BEG');
insert into evugruppe values(HIBERNATE_SEQUENCE.NEXTVAL, 'EBG Altbk');
insert into evugruppe values(HIBERNATE_SEQUENCE.NEXTVAL, 'Railflex');
insert into evugruppe values(HIBERNATE_SEQUENCE.NEXTVAL, 'Hafen Neus');
insert into evugruppe values(HIBERNATE_SEQUENCE.NEXTVAL, 'MVG');
insert into evugruppe values(HIBERNATE_SEQUENCE.NEXTVAL, 'ETS');
insert into evugruppe values(HIBERNATE_SEQUENCE.NEXTVAL, 'Rhenus');
insert into evugruppe values(HIBERNATE_SEQUENCE.NEXTVAL, 'WLE');
insert into evugruppe values(HIBERNATE_SEQUENCE.NEXTVAL, 'Ndrrh. VB.');
insert into evugruppe values(HIBERNATE_SEQUENCE.NEXTVAL, 'Stadt Monh');
insert into evugruppe values(HIBERNATE_SEQUENCE.NEXTVAL, 'Hafen Krf.');
insert into evugruppe values(HIBERNATE_SEQUENCE.NEXTVAL, 'Westerw. B');
insert into evugruppe values(HIBERNATE_SEQUENCE.NEXTVAL, 'Siegener K');
insert into evugruppe values(HIBERNATE_SEQUENCE.NEXTVAL, 'DGEG Bochu');
insert into evugruppe values(HIBERNATE_SEQUENCE.NEXTVAL, 'VEO, TWE');
insert into evugruppe values(HIBERNATE_SEQUENCE.NEXTVAL, 'RVM Münste');
insert into evugruppe values(HIBERNATE_SEQUENCE.NEXTVAL, 'MuseumHamm');
insert into evugruppe values(HIBERNATE_SEQUENCE.NEXTVAL, 'DE Dtm');
insert into evugruppe values(HIBERNATE_SEQUENCE.NEXTVAL, 'Eifelb.');
insert into evugruppe values(HIBERNATE_SEQUENCE.NEXTVAL, 'AAE');
insert into evugruppe values(HIBERNATE_SEQUENCE.NEXTVAL, 'Regio  Met');
insert into evugruppe values(HIBERNATE_SEQUENCE.NEXTVAL, 'Hellertalb');
insert into evugruppe values(HIBERNATE_SEQUENCE.NEXTVAL, 'VEO, RBE');
insert into evugruppe values(HIBERNATE_SEQUENCE.NEXTVAL, 'Almetalb.');
insert into evugruppe values(HIBERNATE_SEQUENCE.NEXTVAL, 'Siemens');
insert into evugruppe values(HIBERNATE_SEQUENCE.NEXTVAL, 'P Cramer');
insert into evugruppe values(HIBERNATE_SEQUENCE.NEXTVAL, 'Glb Kölngl');
insert into evugruppe values(HIBERNATE_SEQUENCE.NEXTVAL, 'J. Hubert');
insert into evugruppe values(HIBERNATE_SEQUENCE.NEXTVAL, 'R.R. Hamm');
insert into evugruppe values(HIBERNATE_SEQUENCE.NEXTVAL, 'DB Glb. Db');
insert into evugruppe values(HIBERNATE_SEQUENCE.NEXTVAL, 'Becker Obh');
insert into evugruppe values(HIBERNATE_SEQUENCE.NEXTVAL, 'Heitkamp');
insert into evugruppe values(HIBERNATE_SEQUENCE.NEXTVAL, 'Lauff GmbH');
insert into evugruppe values(HIBERNATE_SEQUENCE.NEXTVAL, 'VolkerRail');
insert into evugruppe values(HIBERNATE_SEQUENCE.NEXTVAL, 'ELG');
insert into evugruppe values(HIBERNATE_SEQUENCE.NEXTVAL, 'H '||CHR(38)||' M');
insert into evugruppe values(HIBERNATE_SEQUENCE.NEXTVAL, 'Balter');
insert into evugruppe values(HIBERNATE_SEQUENCE.NEXTVAL, 'NS Cargo');
insert into evugruppe values(HIBERNATE_SEQUENCE.NEXTVAL, 'Short Line');
insert into evugruppe values(HIBERNATE_SEQUENCE.NEXTVAL, 'Moerdijk');
insert into evugruppe values(HIBERNATE_SEQUENCE.NEXTVAL, 'AT VRR');
insert into evugruppe values(HIBERNATE_SEQUENCE.NEXTVAL, 'S-Bahn Rhein Main');
insert into evugruppe values(HIBERNATE_SEQUENCE.NEXTVAL, 'Stock');
insert into evugruppe values(HIBERNATE_SEQUENCE.NEXTVAL, 'TransRegio');
insert into evugruppe values(HIBERNATE_SEQUENCE.NEXTVAL, 'HLB, Basis');
insert into evugruppe values(HIBERNATE_SEQUENCE.NEXTVAL, 'Eurolux');
insert into evugruppe values(HIBERNATE_SEQUENCE.NEXTVAL, 'NBE');
insert into evugruppe values(HIBERNATE_SEQUENCE.NEXTVAL, 'HGB');
insert into evugruppe values(HIBERNATE_SEQUENCE.NEXTVAL, 'NBEBombard');
insert into evugruppe values(HIBERNATE_SEQUENCE.NEXTVAL, 'Brohltal');
insert into evugruppe values(HIBERNATE_SEQUENCE.NEXTVAL, 'VEB');
insert into evugruppe values(HIBERNATE_SEQUENCE.NEXTVAL, 'VIAS');
insert into evugruppe values(HIBERNATE_SEQUENCE.NEXTVAL, 'HLB, Hessb');
insert into evugruppe values(HIBERNATE_SEQUENCE.NEXTVAL, 'NVV');
insert into evugruppe values(HIBERNATE_SEQUENCE.NEXTVAL, 'RMV');
insert into evugruppe values(HIBERNATE_SEQUENCE.NEXTVAL, 'TX Log');
insert into evugruppe values(HIBERNATE_SEQUENCE.NEXTVAL, 'Rheinh. Eb');
insert into evugruppe values(HIBERNATE_SEQUENCE.NEXTVAL, 'HWB');
insert into evugruppe values(HIBERNATE_SEQUENCE.NEXTVAL, 'Pollmeier');
insert into evugruppe values(HIBERNATE_SEQUENCE.NEXTVAL, 'GLV');
insert into evugruppe values(HIBERNATE_SEQUENCE.NEXTVAL, 'Mus.Darmst');
insert into evugruppe values(HIBERNATE_SEQUENCE.NEXTVAL, 'DMEisenb');
insert into evugruppe values(HIBERNATE_SEQUENCE.NEXTVAL, 'HLG');
insert into evugruppe values(HIBERNATE_SEQUENCE.NEXTVAL, 'Kombiverk.');
insert into evugruppe values(HIBERNATE_SEQUENCE.NEXTVAL, 'HFM');
insert into evugruppe values(HIBERNATE_SEQUENCE.NEXTVAL, 'Kahlgr.VG');
insert into evugruppe values(HIBERNATE_SEQUENCE.NEXTVAL, 'EFTS');
insert into evugruppe values(HIBERNATE_SEQUENCE.NEXTVAL, 'HLB,vectus');
insert into evugruppe values(HIBERNATE_SEQUENCE.NEXTVAL, 'DB Werke');
insert into evugruppe values(HIBERNATE_SEQUENCE.NEXTVAL, 'Bahntec');
insert into evugruppe values(HIBERNATE_SEQUENCE.NEXTVAL, 'cantus');
insert into evugruppe values(HIBERNATE_SEQUENCE.NEXTVAL, 'Krebs B Mü');
insert into evugruppe values(HIBERNATE_SEQUENCE.NEXTVAL, 'Reisse');
insert into evugruppe values(HIBERNATE_SEQUENCE.NEXTVAL, 'Kaiser  Ta');
insert into evugruppe values(HIBERNATE_SEQUENCE.NEXTVAL, 'Glb. Kobl.');
insert into evugruppe values(HIBERNATE_SEQUENCE.NEXTVAL, 'HartungBau');
insert into evugruppe values(HIBERNATE_SEQUENCE.NEXTVAL, 'DIE-LEI');
insert into evugruppe values(HIBERNATE_SEQUENCE.NEXTVAL, 'DB RNV');
insert into evugruppe values(HIBERNATE_SEQUENCE.NEXTVAL, 'FTZ');
insert into evugruppe values(HIBERNATE_SEQUENCE.NEXTVAL, 'S-Hmbg');
insert into evugruppe values(HIBERNATE_SEQUENCE.NEXTVAL, 'Altona KN');
insert into evugruppe values(HIBERNATE_SEQUENCE.NEXTVAL, 'Weserbahn');
insert into evugruppe values(HIBERNATE_SEQUENCE.NEXTVAL, 'Metronom');
insert into evugruppe values(HIBERNATE_SEQUENCE.NEXTVAL, 'VGH');
insert into evugruppe values(HIBERNATE_SEQUENCE.NEXTVAL, 'EVB');
insert into evugruppe values(HIBERNATE_SEQUENCE.NEXTVAL, 'Nordbahn NBE');
insert into evugruppe values(HIBERNATE_SEQUENCE.NEXTVAL, 'Bentheimer');
insert into evugruppe values(HIBERNATE_SEQUENCE.NEXTVAL, 'Mi-weser');
insert into evugruppe values(HIBERNATE_SEQUENCE.NEXTVAL, 'FSF');
insert into evugruppe values(HIBERNATE_SEQUENCE.NEXTVAL, 'IGT');
insert into evugruppe values(HIBERNATE_SEQUENCE.NEXTVAL, 'DWK');
insert into evugruppe values(HIBERNATE_SEQUENCE.NEXTVAL, 'northrail');
insert into evugruppe values(HIBERNATE_SEQUENCE.NEXTVAL, 'TELH');
insert into evugruppe values(HIBERNATE_SEQUENCE.NEXTVAL, 'CFL');
insert into evugruppe values(HIBERNATE_SEQUENCE.NEXTVAL, 'EVERS');
insert into evugruppe values(HIBERNATE_SEQUENCE.NEXTVAL, 'VEO, FVE');
insert into evugruppe values(HIBERNATE_SEQUENCE.NEXTVAL, 'ARR, OHE');
insert into evugruppe values(HIBERNATE_SEQUENCE.NEXTVAL, 'boxXpress');
insert into evugruppe values(HIBERNATE_SEQUENCE.NEXTVAL, 'neg');
insert into evugruppe values(HIBERNATE_SEQUENCE.NEXTVAL, 'Schleswig-Holstein-Bahn');
insert into evugruppe values(HIBERNATE_SEQUENCE.NEXTVAL, 'SchenkScan');
insert into evugruppe values(HIBERNATE_SEQUENCE.NEXTVAL, 'BBL Log');
insert into evugruppe values(HIBERNATE_SEQUENCE.NEXTVAL, 'HBG-HI');
insert into evugruppe values(HIBERNATE_SEQUENCE.NEXTVAL, 'HECTORRAIL');
insert into evugruppe values(HIBERNATE_SEQUENCE.NEXTVAL, 'F.E.G.');
insert into evugruppe values(HIBERNATE_SEQUENCE.NEXTVAL, 'VEO, NWB');
insert into evugruppe values(HIBERNATE_SEQUENCE.NEXTVAL, 'egoo');
insert into evugruppe values(HIBERNATE_SEQUENCE.NEXTVAL, 'DP');
insert into evugruppe values(HIBERNATE_SEQUENCE.NEXTVAL, 'SES');
insert into evugruppe values(HIBERNATE_SEQUENCE.NEXTVAL, 'BeNEX');
insert into evugruppe values(HIBERNATE_SEQUENCE.NEXTVAL, 'IBF');
insert into evugruppe values(HIBERNATE_SEQUENCE.NEXTVAL, 'HEG');
insert into evugruppe values(HIBERNATE_SEQUENCE.NEXTVAL, 'Wittfeld');
insert into evugruppe values(HIBERNATE_SEQUENCE.NEXTVAL, 'Transpetro');
insert into evugruppe values(HIBERNATE_SEQUENCE.NEXTVAL, 'MKB');
insert into evugruppe values(HIBERNATE_SEQUENCE.NEXTVAL, 'Vossloh');
insert into evugruppe values(HIBERNATE_SEQUENCE.NEXTVAL, 'VVM Schönb');
insert into evugruppe values(HIBERNATE_SEQUENCE.NEXTVAL, 'Hafen Kiel');
insert into evugruppe values(HIBERNATE_SEQUENCE.NEXTVAL, 'Delmh. Eb.');
insert into evugruppe values(HIBERNATE_SEQUENCE.NEXTVAL, 'Emsl. Eb.');
insert into evugruppe values(HIBERNATE_SEQUENCE.NEXTVAL, 'Brm. Thedh');
insert into evugruppe values(HIBERNATE_SEQUENCE.NEXTVAL, 'VPS Peine');
insert into evugruppe values(HIBERNATE_SEQUENCE.NEXTVAL, 'Warnetalb.');
insert into evugruppe values(HIBERNATE_SEQUENCE.NEXTVAL, 'Verden Wal');
insert into evugruppe values(HIBERNATE_SEQUENCE.NEXTVAL, 'Vorw. Emmt');
insert into evugruppe values(HIBERNATE_SEQUENCE.NEXTVAL, 'VG. Lk.Osn');
insert into evugruppe values(HIBERNATE_SEQUENCE.NEXTVAL, 'Mus. Ostfr');
insert into evugruppe values(HIBERNATE_SEQUENCE.NEXTVAL, 'Ilmetalbah');
insert into evugruppe values(HIBERNATE_SEQUENCE.NEXTVAL, 'MAS');
insert into evugruppe values(HIBERNATE_SEQUENCE.NEXTVAL, 'MuseumBrhv');
insert into evugruppe values(HIBERNATE_SEQUENCE.NEXTVAL, 'VEO, NOB');
insert into evugruppe values(HIBERNATE_SEQUENCE.NEXTVAL, 'NORDIC');
insert into evugruppe values(HIBERNATE_SEQUENCE.NEXTVAL, 'VGT');
insert into evugruppe values(HIBERNATE_SEQUENCE.NEXTVAL, 'NBI4');
insert into evugruppe values(HIBERNATE_SEQUENCE.NEXTVAL, 'Steinbrech');
insert into evugruppe values(HIBERNATE_SEQUENCE.NEXTVAL, 'Schweer');
insert into evugruppe values(HIBERNATE_SEQUENCE.NEXTVAL, 'Wiebe');
insert into evugruppe values(HIBERNATE_SEQUENCE.NEXTVAL, 'Schneider');
insert into evugruppe values(HIBERNATE_SEQUENCE.NEXTVAL, 'LDS');
insert into evugruppe values(HIBERNATE_SEQUENCE.NEXTVAL, 'HSL');
insert into evugruppe values(HIBERNATE_SEQUENCE.NEXTVAL, 'Strube');
insert into evugruppe values(HIBERNATE_SEQUENCE.NEXTVAL, 'KubeCon');
insert into evugruppe values(HIBERNATE_SEQUENCE.NEXTVAL, 'DSB Goods');
insert into evugruppe values(HIBERNATE_SEQUENCE.NEXTVAL, 'PBS');
insert into evugruppe values(HIBERNATE_SEQUENCE.NEXTVAL, 'Maersk');
insert into evugruppe values(HIBERNATE_SEQUENCE.NEXTVAL, 'AT LVS');
insert into evugruppe values(HIBERNATE_SEQUENCE.NEXTVAL, 'AT LNVG');
insert into evugruppe values(HIBERNATE_SEQUENCE.NEXTVAL, 'AT ZGB');
insert into evugruppe values(HIBERNATE_SEQUENCE.NEXTVAL, 'KTG');
insert into evugruppe values(HIBERNATE_SEQUENCE.NEXTVAL, 'RS AN');
insert into evugruppe values(HIBERNATE_SEQUENCE.NEXTVAL, 'St Wendel');
insert into evugruppe values(HIBERNATE_SEQUENCE.NEXTVAL, 'SBB, Pv');
insert into evugruppe values(HIBERNATE_SEQUENCE.NEXTVAL, 'HUPAC');
insert into evugruppe values(HIBERNATE_SEQUENCE.NEXTVAL, 'SBB, Cargo');
insert into evugruppe values(HIBERNATE_SEQUENCE.NEXTVAL, 'BahnLog');
insert into evugruppe values(HIBERNATE_SEQUENCE.NEXTVAL, 'NeSA');
insert into evugruppe values(HIBERNATE_SEQUENCE.NEXTVAL, 'VEO, WEG');
insert into evugruppe values(HIBERNATE_SEQUENCE.NEXTVAL, 'ESG Augsbg');
insert into evugruppe values(HIBERNATE_SEQUENCE.NEXTVAL, 'CargoRail');
insert into evugruppe values(HIBERNATE_SEQUENCE.NEXTVAL, 'HZL');
insert into evugruppe values(HIBERNATE_SEQUENCE.NEXTVAL, 'Schönbuchb');
insert into evugruppe values(HIBERNATE_SEQUENCE.NEXTVAL, 'Bräunert');
insert into evugruppe values(HIBERNATE_SEQUENCE.NEXTVAL, 'RP Eisenb.');
insert into evugruppe values(HIBERNATE_SEQUENCE.NEXTVAL, 'AVG');
insert into evugruppe values(HIBERNATE_SEQUENCE.NEXTVAL, 'BLS Cargo');
insert into evugruppe values(HIBERNATE_SEQUENCE.NEXTVAL, 'TIM Rail');
insert into evugruppe values(HIBERNATE_SEQUENCE.NEXTVAL, 'RST St.Ing');
insert into evugruppe values(HIBERNATE_SEQUENCE.NEXTVAL, 'SAB');
insert into evugruppe values(HIBERNATE_SEQUENCE.NEXTVAL, 'L. Weiss');
insert into evugruppe values(HIBERNATE_SEQUENCE.NEXTVAL, 'UTL-GmbH');
insert into evugruppe values(HIBERNATE_SEQUENCE.NEXTVAL, 'RAR');
insert into evugruppe values(HIBERNATE_SEQUENCE.NEXTVAL, 'SPNV Süd');
insert into evugruppe values(HIBERNATE_SEQUENCE.NEXTVAL, 'THURBO AG');
insert into evugruppe values(HIBERNATE_SEQUENCE.NEXTVAL, 'MEV');
insert into evugruppe values(HIBERNATE_SEQUENCE.NEXTVAL, 'GfE');
insert into evugruppe values(HIBERNATE_SEQUENCE.NEXTVAL, 'AERS');
insert into evugruppe values(HIBERNATE_SEQUENCE.NEXTVAL, 'Eurovapor');
insert into evugruppe values(HIBERNATE_SEQUENCE.NEXTVAL, 'Kandertalb');
insert into evugruppe values(HIBERNATE_SEQUENCE.NEXTVAL, 'Kuckucksb.');
insert into evugruppe values(HIBERNATE_SEQUENCE.NEXTVAL, 'Elsenzb.');
insert into evugruppe values(HIBERNATE_SEQUENCE.NEXTVAL, 'SWEG');
insert into evugruppe values(HIBERNATE_SEQUENCE.NEXTVAL, 'BASF');
insert into evugruppe values(HIBERNATE_SEQUENCE.NEXTVAL, 'Wutachb.');
insert into evugruppe values(HIBERNATE_SEQUENCE.NEXTVAL, 'Pfalzb.');
insert into evugruppe values(HIBERNATE_SEQUENCE.NEXTVAL, 'MECL Losh.');
insert into evugruppe values(HIBERNATE_SEQUENCE.NEXTVAL, 'Saarbahn');
insert into evugruppe values(HIBERNATE_SEQUENCE.NEXTVAL, 'EMN');
insert into evugruppe values(HIBERNATE_SEQUENCE.NEXTVAL, 'SchieneStg');
insert into evugruppe values(HIBERNATE_SEQUENCE.NEXTVAL, 'SWEG,BrsgS');
insert into evugruppe values(HIBERNATE_SEQUENCE.NEXTVAL, 'Wincanton');
insert into evugruppe values(HIBERNATE_SEQUENCE.NEXTVAL, 'SWEG, OrtS');
insert into evugruppe values(HIBERNATE_SEQUENCE.NEXTVAL, 'UEF');
insert into evugruppe values(HIBERNATE_SEQUENCE.NEXTVAL, 'Bod-Obsch.');
insert into evugruppe values(HIBERNATE_SEQUENCE.NEXTVAL, 'Zürcher');
insert into evugruppe values(HIBERNATE_SEQUENCE.NEXTVAL, 'Monti');
insert into evugruppe values(HIBERNATE_SEQUENCE.NEXTVAL, 'ELBA');
insert into evugruppe values(HIBERNATE_SEQUENCE.NEXTVAL, 'CD');
insert into evugruppe values(HIBERNATE_SEQUENCE.NEXTVAL, 'EB+STB');
insert into evugruppe values(HIBERNATE_SEQUENCE.NEXTVAL, 'Heavy Haul');
insert into evugruppe values(HIBERNATE_SEQUENCE.NEXTVAL, 'LEG');
insert into evugruppe values(HIBERNATE_SEQUENCE.NEXTVAL, 'Mansf.');
insert into evugruppe values(HIBERNATE_SEQUENCE.NEXTVAL, 'Ferropolis');
insert into evugruppe values(HIBERNATE_SEQUENCE.NEXTVAL, 'MTEG');
insert into evugruppe values(HIBERNATE_SEQUENCE.NEXTVAL, 'ITB Brbg.');
insert into evugruppe values(HIBERNATE_SEQUENCE.NEXTVAL, 'VEO, MRB');
insert into evugruppe values(HIBERNATE_SEQUENCE.NEXTVAL, 'SKL');
insert into evugruppe values(HIBERNATE_SEQUENCE.NEXTVAL, 'VSE');
insert into evugruppe values(HIBERNATE_SEQUENCE.NEXTVAL, 'Sä-Oberlau');
insert into evugruppe values(HIBERNATE_SEQUENCE.NEXTVAL, 'Mi-dt Eb.');
insert into evugruppe values(HIBERNATE_SEQUENCE.NEXTVAL, 'Arco');
insert into evugruppe values(HIBERNATE_SEQUENCE.NEXTVAL, 'ITL Cargo');
insert into evugruppe values(HIBERNATE_SEQUENCE.NEXTVAL, 'RBG');
insert into evugruppe values(HIBERNATE_SEQUENCE.NEXTVAL, 'AWV');
insert into evugruppe values(HIBERNATE_SEQUENCE.NEXTVAL, 'KSV');
insert into evugruppe values(HIBERNATE_SEQUENCE.NEXTVAL, 'EBS');
insert into evugruppe values(HIBERNATE_SEQUENCE.NEXTVAL, 'VEO, HEX');
insert into evugruppe values(HIBERNATE_SEQUENCE.NEXTVAL, 'ARR, VLB');
insert into evugruppe values(HIBERNATE_SEQUENCE.NEXTVAL, 'WEV');
insert into evugruppe values(HIBERNATE_SEQUENCE.NEXTVAL, 'RIS');
insert into evugruppe values(HIBERNATE_SEQUENCE.NEXTVAL, 'ITL SNCF');
insert into evugruppe values(HIBERNATE_SEQUENCE.NEXTVAL, 'ODIN');
insert into evugruppe values(HIBERNATE_SEQUENCE.NEXTVAL, 'ITL');
insert into evugruppe values(HIBERNATE_SEQUENCE.NEXTVAL, 'RDX');
insert into evugruppe values(HIBERNATE_SEQUENCE.NEXTVAL, 'PBG');
insert into evugruppe values(HIBERNATE_SEQUENCE.NEXTVAL, 'POR');
insert into evugruppe values(HIBERNATE_SEQUENCE.NEXTVAL, 'ITL Benelux');
insert into evugruppe values(HIBERNATE_SEQUENCE.NEXTVAL, 'TfR');
insert into evugruppe values(HIBERNATE_SEQUENCE.NEXTVAL, 'Walthelm');
insert into evugruppe values(HIBERNATE_SEQUENCE.NEXTVAL, 'Erfurt IG');
insert into evugruppe values(HIBERNATE_SEQUENCE.NEXTVAL, 'Loburger');
insert into evugruppe values(HIBERNATE_SEQUENCE.NEXTVAL, 'Wismut');
insert into evugruppe values(HIBERNATE_SEQUENCE.NEXTVAL, 'Krb. Mansf');
insert into evugruppe values(HIBERNATE_SEQUENCE.NEXTVAL, 'InfraLeuna');
insert into evugruppe values(HIBERNATE_SEQUENCE.NEXTVAL, 'ABG Dessau');
insert into evugruppe values(HIBERNATE_SEQUENCE.NEXTVAL, 'Kirow');
insert into evugruppe values(HIBERNATE_SEQUENCE.NEXTVAL, 'HSB Wernig');
insert into evugruppe values(HIBERNATE_SEQUENCE.NEXTVAL, 'VEO, HTB');
insert into evugruppe values(HIBERNATE_SEQUENCE.NEXTVAL, 'Stahlw. Th');
insert into evugruppe values(HIBERNATE_SEQUENCE.NEXTVAL, 'Trb. Radeb');
insert into evugruppe values(HIBERNATE_SEQUENCE.NEXTVAL, 'CB Chem');
insert into evugruppe values(HIBERNATE_SEQUENCE.NEXTVAL, 'ITL EGG');
insert into evugruppe values(HIBERNATE_SEQUENCE.NEXTVAL, 'Lappwaldb.');
insert into evugruppe values(HIBERNATE_SEQUENCE.NEXTVAL, 'ITL BL');
insert into evugruppe values(HIBERNATE_SEQUENCE.NEXTVAL, 'SDG');
insert into evugruppe values(HIBERNATE_SEQUENCE.NEXTVAL, 'W-Dessau');
insert into evugruppe values(HIBERNATE_SEQUENCE.NEXTVAL, 'Alstom');
insert into evugruppe values(HIBERNATE_SEQUENCE.NEXTVAL, 'Werk Mein.');
insert into evugruppe values(HIBERNATE_SEQUENCE.NEXTVAL, 'JumboTec');
insert into evugruppe values(HIBERNATE_SEQUENCE.NEXTVAL, 'Glb Buschi');
insert into evugruppe values(HIBERNATE_SEQUENCE.NEXTVAL, 'Glb Erfurt');
insert into evugruppe values(HIBERNATE_SEQUENCE.NEXTVAL, 'Lotrac');
insert into evugruppe values(HIBERNATE_SEQUENCE.NEXTVAL, 'ThE');
insert into evugruppe values(HIBERNATE_SEQUENCE.NEXTVAL, 'MEB');
insert into evugruppe values(HIBERNATE_SEQUENCE.NEXTVAL, 'A.V.G');
insert into evugruppe values(HIBERNATE_SEQUENCE.NEXTVAL, 'IPZ');
insert into evugruppe values(HIBERNATE_SEQUENCE.NEXTVAL, 'RTL');
insert into evugruppe values(HIBERNATE_SEQUENCE.NEXTVAL, 'LUS');
insert into evugruppe values(HIBERNATE_SEQUENCE.NEXTVAL, 'DB BB GmbH');
insert into evugruppe values(HIBERNATE_SEQUENCE.NEXTVAL, 'ZVNL');
insert into evugruppe values(HIBERNATE_SEQUENCE.NEXTVAL, 'VVO');
insert into evugruppe values(HIBERNATE_SEQUENCE.NEXTVAL, 'ZVON');
insert into evugruppe values(HIBERNATE_SEQUENCE.NEXTVAL, 'ZVMS');
insert into evugruppe values(HIBERNATE_SEQUENCE.NEXTVAL, 'VVV');
insert into evugruppe values(HIBERNATE_SEQUENCE.NEXTVAL, 'NASA');
insert into evugruppe values(HIBERNATE_SEQUENCE.NEXTVAL, 'NVS');
insert into evugruppe values(HIBERNATE_SEQUENCE.NEXTVAL, 'BCB');
insert into evugruppe values(HIBERNATE_SEQUENCE.NEXTVAL, 'Lokomotion');
insert into evugruppe values(HIBERNATE_SEQUENCE.NEXTVAL, 'RCN');
insert into evugruppe values(HIBERNATE_SEQUENCE.NEXTVAL, 'SRS');
insert into evugruppe values(HIBERNATE_SEQUENCE.NEXTVAL, 'ARR, Regen');
insert into evugruppe values(HIBERNATE_SEQUENCE.NEXTVAL, 'BBGStauden');
insert into evugruppe values(HIBERNATE_SEQUENCE.NEXTVAL, 'ÖBB (GV)');
insert into evugruppe values(HIBERNATE_SEQUENCE.NEXTVAL, 'IGE');
insert into evugruppe values(HIBERNATE_SEQUENCE.NEXTVAL, 'ÖBB (PV)');
insert into evugruppe values(HIBERNATE_SEQUENCE.NEXTVAL, 'VEO, BRB');
insert into evugruppe values(HIBERNATE_SEQUENCE.NEXTVAL, 'SLB');
insert into evugruppe values(HIBERNATE_SEQUENCE.NEXTVAL, 'PCT');
insert into evugruppe values(HIBERNATE_SEQUENCE.NEXTVAL, 'RBS');
insert into evugruppe values(HIBERNATE_SEQUENCE.NEXTVAL, 'MRCE');
insert into evugruppe values(HIBERNATE_SEQUENCE.NEXTVAL, 'RTS');
insert into evugruppe values(HIBERNATE_SEQUENCE.NEXTVAL, 'Bay.hafen');
insert into evugruppe values(HIBERNATE_SEQUENCE.NEXTVAL, 'RC_Nuernbg');
insert into evugruppe values(HIBERNATE_SEQUENCE.NEXTVAL, 'SGL');
insert into evugruppe values(HIBERNATE_SEQUENCE.NEXTVAL, 'RailAdvent');
insert into evugruppe values(HIBERNATE_SEQUENCE.NEXTVAL, 'Aicher');
insert into evugruppe values(HIBERNATE_SEQUENCE.NEXTVAL, 'IGEBA');
insert into evugruppe values(HIBERNATE_SEQUENCE.NEXTVAL, 'Agilis');
insert into evugruppe values(HIBERNATE_SEQUENCE.NEXTVAL, 'BayernBahn');
insert into evugruppe values(HIBERNATE_SEQUENCE.NEXTVAL, 'Augsbg Lb.');
insert into evugruppe values(HIBERNATE_SEQUENCE.NEXTVAL, 'DFS  Eber');
insert into evugruppe values(HIBERNATE_SEQUENCE.NEXTVAL, 'FME Nbg');
insert into evugruppe values(HIBERNATE_SEQUENCE.NEXTVAL, 'VEO, BOB');
insert into evugruppe values(HIBERNATE_SEQUENCE.NEXTVAL, 'Glb Münche');
insert into evugruppe values(HIBERNATE_SEQUENCE.NEXTVAL, 'Riebel');
insert into evugruppe values(HIBERNATE_SEQUENCE.NEXTVAL, 'H. Joseph');
insert into evugruppe values(HIBERNATE_SEQUENCE.NEXTVAL, 'Europool');
insert into evugruppe values(HIBERNATE_SEQUENCE.NEXTVAL, 'DB Glb Aug');
insert into evugruppe values(HIBERNATE_SEQUENCE.NEXTVAL, 'SGL Carbon');
insert into evugruppe values(HIBERNATE_SEQUENCE.NEXTVAL, 'S-Bahn München');
insert into evugruppe values(HIBERNATE_SEQUENCE.NEXTVAL, 'GYSEV');
insert into evugruppe values(HIBERNATE_SEQUENCE.NEXTVAL, 'Ökombi');
insert into evugruppe values(HIBERNATE_SEQUENCE.NEXTVAL, 'BEG BayEG');
insert into evugruppe values(HIBERNATE_SEQUENCE.NEXTVAL, 'DB Notfall');
insert into evugruppe values(HIBERNATE_SEQUENCE.NEXTVAL, 'DB Fernv');
insert into evugruppe values(HIBERNATE_SEQUENCE.NEXTVAL, 'DB AutoZug');
insert into evugruppe values(HIBERNATE_SEQUENCE.NEXTVAL, 'DB Museum');
insert into evugruppe values(HIBERNATE_SEQUENCE.NEXTVAL, 'EIBV');
commit;