package db.training.osb.web.imports;

public enum ImportTable {
	MASSNAHMEN, GLEISSPERRUNGEN, TOPPROJEKTE, BUENDEL, FAHRPLANREGELUNGEN, UMLEITUNGEN,
	UMLEITUNGSWEGE, PAKETE,

	TOPPROJEKTE_MASSNAHMEN, GLEISSPERRUNGEN_BUENDEL,
	BUENDEL_FAHRPLANREGELUNGEN, UMLEITUNGEN_FAHRPLANREGELUNGEN, UMLEITUNGEN_UMLEITUNGSWEGE
}
